name: Build wkhtmltopdf 0.12.6 (Static All Platforms)

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        os: [centos, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: wkhtmltopdf/wkhtmltopdf
          ref: 0.12.6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            python3 \
            git \
            qemu-user-static \
            docker.io

      - name: Clone packaging repo
        run: |
          git clone https://github.com/wkhtmltopdf/packaging.git

      - name: Build static binary
        run: |
          cd packaging/static-build
          ./build.py \
            --platform=${{ matrix.os }}-${{ matrix.arch }} \
            --wkhtmltopdf-version=0.12.6 \
            --output-dir=output

      - name: Package artifact
        run: |
          cd packaging/static-build/output
          tar czvf wkhtmltopdf-0.12.6-${{ matrix.os }}-${{ matrix.arch }}.tar.gz wkhtmltopdf
          mkdir -p ../../artifacts
          mv wkhtmltopdf-0.12.6-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ../../artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wkhtmltopdf-${{ matrix.os }}-${{ matrix.arch }}
          path: packaging/static-build/artifacts/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: wkhtmltopdf-0.12.6
          name: wkhtmltopdf 0.12.6 Static Build
          body: |
            This release contains statically compiled wkhtmltopdf 0.12.6 binaries for:
            - CentOS x86_64
            - CentOS ARM64
            - Ubuntu x86_64
            - Ubuntu ARM64

            These binaries are fully static and can run without additional dependencies.
          files: ./release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
