name: Build wkhtmltopdf static x86_64

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'wkhtmltopdf version tag'
        default: '0.12.6'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow files
        uses: actions/checkout@v4

      - name: Build Docker image for static build
        run: |
          docker build \
            --build-arg WKHTMLTOPDF_VERSION=${{ github.event.inputs.version }} \
            -t wkhtmltopdf-builder .

      - name: Run build in Docker
        run: |
          mkdir -p output
          docker run --rm \
            -v ${{ github.workspace }}/output:/output \
            wkhtmltopdf-builder \
            /bin/bash -c "scripts/build-static.sh && cp bin/wkhtmltopdf /output/wkhtmltopdf-x86_64"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wkhtmltopdf-x86_64
          path: output/wkhtmltopdf-x86_64
